spring:
  application:
    name: cloud-boot-adminserver
  redis:
    host: 42.192.87.137
    port: 6379
    lettuce:
      pool:
        max-active: 8
    connect-timeout: 60000
    timeout: 1
server:
  port: 8788