spring:
  jackson:
    #序列化时属性处理,所有类型 See JsonInclude.Include non_null:不包含值为null的属性
    default-property-inclusion: non_null
  application:
    # 应用名
    name: cloud-monitor-center
server:
  #web端口
  port: 9001
logging:
  #日志级别
  level:
    root: info
  file:
    path: ./logs
  config: classpath:logback-spring.xml
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always