spring:
  datasource:
    url: jdbc:mysql://localhost:3306/search?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8088

elasticsearch:
  host: localhost
  port: 9200
