spring:
  application:
    name: @artifactId@
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:p6spy:mysql://127.0.0.1:3306/sloars?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  resources:
    chain:
      cache: false
  thymeleaf:
    cache: false
  jpa:
    show-sql: true
    #generate-ddl: true
    hibernate:
      ddl-auto: update
server:
  port: 9001

eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://122.51.108.224:8001/eureka/
    enabled: false
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health
logging:
  level:
    root: INFO