spring:
  application:
    name: cloud-dubbo-consumer
dubbo:
  protocol:
    name: dubbo
    port: -1
  registry:
    address: zookeeper://122.51.108.224:2181
  consumer:
    check: false
server:
  port: 8081
