spring:
  application:
    name: cloud-dubbo-consumer
dubbo:
  scan:
    base-packages: om.open.cloud.dubbo.consumer
  protocol:
    name: dubbo
    port: -1
  registry:
    address: zookeeper://122.51.108.224:2181
server:
  port: 8081
feign:
  hystrix:
    enabled: true
