spring:
  application:
    name: spring-cloud-gateway
  http:
    encoding:
      charset: UTF-8
      enable: true
      force: true
  messages:
    encoding: UTF-8
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 2000ms
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      routes:
      - id: ingredients
        uri: lb://hello-world
        predicates:
        - Path=//newhelloworld/**
        filters:
        - RewritePath=/newhelloworld/(?<segment>.*), /$\{segment}
#      routes:
#        - id: test-demo
#          uri: lb://demo-service
#          order: 0
#          predicates:
#            - Path=/demo-service/**
#            - Header=Version, V1.0
#          filters:
#            - RewritePath=/demo-service/(?<segment>.*), /$\{segment}

server:
  port: 8081
  tomcat:
    accept-count: 15000
    max-threads: 2000
    max-connections: 15000
  servlet:
    context-path: /

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://127.0.0.1:8001/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    metadataMap:
      version: 1.0


management:
  endpoints:
    web:
      exposure:
        include: '*'
    security:
      enabled: false
json:
  predicate:
    path: gateway\src\main\resources\predicate.json
  filter:
    path: gateway\src\main\resources\filter.json
  resolver:
    path: gateway\src\main\resources\resolver.json
  headers:
    path: gateway\src\main\resources\headers.json

timer:
  delay: 30
  period: 30
hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000
    #hello-world:
    #ribbon:
    #ReadTimeout: 1000
    #ConnectTimeout: 1000
    #NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
ribbon:
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule

threadpool:
  default:
    coreSize: 32
    maximumSize: 32
    allowMaximumSizeToDivergeFromCoreSize: true
    maxQueueSize: 100000
logging:
  level:
    #    org.springframework.cloud.gateway: TRACE
    #    org.springframework.http.server.reactive: DEBUG
    #    org.springframework.web.reactive: DEBUG
    #    reactor.ipc.netty: DEBUG
    root: INFO
    org.springframework.boot.autoconfigure.web.reactive.error.DefaultErrorWebExceptionHandler: DEBUG
