spring:
  application:
    name: cloud-boot-springcloud-provider
server:
  #web端口
  port: 18081
eureka:
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 15 #服务过期时间
    lease-renewal-interval-in-seconds: 5 #服务刷新时间,每5s心跳一次
  client:
    enabled: true
    #是否注册至eureka
    register-with-eureka: true
    #是否获取注册表
    fetch-registry: true
    #service-url:
    #defaultZone: http://127.0.0.1:8761/eureka/
    healthcheck:
      enabled: false
    eurekaServiceUrlPollIntervalSeconds: 60
    #设置拉取服务注册信息时间
    registry-fetch-interval-seconds: 5
      #eureka:
      #instance:
      #prefer-ip-address: true
      #status-page-url-path: /actuator/info
      #health-check-url-path: /actuator/health
      #client:
      #register-with-eureka: true
      #fetch-registry: true
      #prefer-same-zone-eureka: true
      #地区
      #region: tangshan
      #service-url:
      #DC1: http://peer1.com:9801/eureka/
    #DC2: http://peer2.com:9802/eureka/
    #DC3: http://peer3.com:9803/eureka/
    region: beijing
---
server:
  #web端口
  port: 18081
eureka:
  instance:
    metadata-map:
      zone: DC1
  client:
    availability-zones:
      tangshan: DC1,DC2
    region: tangshan
    service-url:
      DC1: http://42.192.87.137:9801/eureka/
      DC2: http://42.192.87.137:9802/eureka/
    prefer-same-zone-eureka: true
spring:
  config:
    activate:
      on-profile: peer1
---
server:
  #web端口
  port: 18082
eureka:
  instance:
    metadata-map:
      zone: DC2
  client:
    availability-zones:
      tangshan: DC2,DC1
    region: tangshan
    service-url:
      DC2: http://42.192.87.137:9802/eureka/
      DC1: http://42.192.87.137:9801/eureka/
    prefer-same-zone-eureka: true
spring:
  config:
    activate:
      on-profile: peer2
---

