spring:
  application:
    name: cloud-zuul-gateway

server:
  port: 9001

eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://10.7.19.103:8761/eureka/
  instance:
    prefer-ip-address: true

zuul:
  routes:
    api-a:
      path: /sayHello/**
      serviceId: CLOUD-EUREKA-SERVICE
      stripPrefix: false
