server:
  port: 8080
spring:
  application:
    name: spring-cloud-nacos-gateway
  cloud:
    nacos:
      config:
        server-addr: 122.51.108.224:8848
management:
  endpoints:
    web:
      exposure:
        include: '*'