spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        metadata:
          node: ${spring.application.name}
    loadbalancer:
      retry:
        enabled: false
      configurations: zone-preference
logging:
  #logback地址
  config: classpath:logback-spring.xml
  level:
    root: INFO