spring:
  application:
    name: alibaba-provider-examples
  cloud:
    nacos:
      discovery:
        server-addr: 42.192.87.137:18848
logging:
  #logback地址
  config: classpath:logback-spring.xml
  level:
    root: INFO