spring:
  application:
    name: alibaba-provider-examples
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
logging:
  #logback地址
  config: classpath:logback-spring.xml
  level:
    root: INFO