spring:
  application:
    name: alibaba-provider-examples
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    loadbalancer:
      retry:
        enabled: false
      configurations: zone-preference
  profiles:
    active: dev
logging:
  level:
    root: INFO