package rules.first;

import com.learn.model.Student

global String str;

rule "myTest one"
	dialect "java"
	no-loop true
	lock-on-active true
    activation-group "myTest"
    salience 20
	when
        std:Student(age > 10)
	then
	    std.setMessage(str + ":priority-20");

end


rule "myTest two"
	dialect "java"
	no-loop true
	lock-on-active true
    activation-group "myTest"
    salience 30
	when
        std:Student(age > 10)
	then
        std.setMessage(str + ":priority-30");
end

