spring:
  application:
    name: cloud-boot-springcloud-consumer
eureka:
  instance:
    prefer-ip-address: true
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health
  client:
    register-with-eureka: true
    fetch-registry: true
    prefer-same-zone-eureka: true
    #地区
    region: tangshan
    service-url:
      DC1: http://peer1.com:9801/eureka/
      DC2: http://peer2.com:9802/eureka/
      DC3: http://peer3.com:9803/eureka/
feign:
  hystrix:
    enabled: true
  compression:
    request:
      enabled: true
    response:
      enabled: true
  client:
    config:
      default:
        #error-decoder: com.example.feign.MyErrorDecoder
        connectTimeout: 50000
      cloud-boot-springcloud-provider:
        connectTimeout: 50002
    enabled: false
  okhttp:
    enabled: true
hystrix:
  dashboard:
    proxy-stream-allow-list: '*'
logging:
  level:
    com.open.cloud.springcloud.consumer.service: DEBUG
ribbon:
  okhttp:
    enabled: true
---
spring:
  profiles: dev
server:
  port: 28081
eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health
  client:
    register-with-eureka: true
    fetch-registry: true
    prefer-same-zone-eureka: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
  #      defaultZone: http://127.0.0.1:10011/eureka/
  #      zone-1: http://127.0.0.1:10011/eureka/
  #      zone-2: http://127.0.0.1:10012/eureka/,http://127.0.0.1:10013/eureka/
  #    region: beijing
  #    availability-zones:
  #      beijing: zone-1,zone-2,zone-3
---
server:
  #web端口
  port: 28081
eureka:
  instance:
    metadata-map:
      zone: DC1
  client:
    availability-zones:
      tangshan: DC1,DC2,DC3
spring:
  profiles: peer1
---
---
server:
  #web端口
  port: 28082
eureka:
  instance:
    metadata-map:
      zone: DC2
  client:
    availability-zones:
      tangshan: DC2,DC1,DC3
spring:
  profiles: peer2
---

