spring:
  application:
    name: spring-cloud-gateway
  http:
    encoding:
      charset: UTF-8
      enable: true
      force: true
  messages:
    encoding: UTF-8
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          #lowerCaseServiceId: true
      routes:
        - id: path_route
          uri: lb://CLOUD-EUREKA-SERVICE
          order: 0
          predicates:
            - Path=/sayHello/**
          filters:
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY
            - name: Hystrix
              args:
                name: fallbackcmd
                fallbackUri: forward:/incaseoffailureusethis
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10 #允许用户每秒处理多少个请求
                redis-rate-limiter.burstCapacity: 20 #令牌桶的容量，允许在一秒钟内完成的最大请求数
                key-resolver: "#{@userKeyResolver}" #使用 SpEL 按名称引用 bean
  redis:
    host: 127.0.0.1

server:
  port: 9002

feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
    
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://122.51.108.224:8001/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health

management:
  endpoints:
    web:
      exposure:
        include: '*'
    security:
      enabled: false