spring:
  application:
    name: cloud-eureka-service
  zipkin:
    base-url: http://122.51.108.224:9411
server:
  port: 7001

eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://122.51.108.224:8001/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health
com:
  alipay:
    sofa:
      tracer:
        zipkin:
          base-url: http://122.51.108.224:9411
        springmvc:
          url-patterns: /**