spring:
  application:
    name: cloud-eureka-service
server:
  port: 7001

eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://10.7.19.103:8761/eureka/
  instance:
    prefer-ip-address: true
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health