spring:
  application:
    name: auth-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.7.25.205:3306/workflow?characterEncoding=utf-8&useSSL=false
    password: root
    username: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      username: root
      password: 123456
  redis:
    host: 10.7.20.151
    port: 7379
server:
  port: 6001
management:
  endpoint:
    health:
      enabled: true
#分页查询配置
pagehelper:
  reasonable: true
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    database-id: mmysql
logging:
  level:
    org.springframework.security: TRACE