spring:
  application:
    name: springboot-batch
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/batch?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: ENC(KzQf/FFIWhYZvRB9PKzzog==)
    password: ENC(KzQf/FFIWhYZvRB9PKzzog==)
jasypt:
  encryptor:
    password: 1Qaz0oKm
logging:
  level:
    root: debug
