spring:
  profiles:
    active: dev
  application:
    name: drools-svc

#配置日志
logging:
  config: classpath:log/logback-spring.xml


swagger:
  #作者
  author: ys
  #接口标题
  title: Drools规则引擎用例
  #接口描叙
  description: 规则引擎接口
  #版本
  version: 1.0.0
  #具体对外暴露的接口类的包地址 暴露以下包所有的对外提供的接口
  basePackage: com.learn.controller
