spring:
  application:
    name: cloud-dubbo-provider
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://10.7.25.205:3306/workflow?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8080
mybatis-plus:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath*:/mapper/**/*.xml
logging:
  level:
    root: INFO
    com.open.cloud.dubbo.provider.dao: DEBUG
    org.mybatis: debug
    "com.alipay.sofa": DEBUG
    org.apache.ibatis: debug
    com.baomidou.mybatisplus: debug
    org.springframework.jdbc: debug
  file:
    path: ./logs
com:
  alipay:
    sofa:
      rpc:
        registry-address: nacos://122.51.108.224:8848/public
