spring:
  application:
    name: cloud-sofa-provider
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/workflow?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
server:
  port: 8080
mybatis-plus:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath*:/mapper/**/*.xml
logging:
  level:
    root: INFO
    com.open.cloud.dubbo.provider.dao: DEBUG
    org.mybatis: debug
    com.alipay.sofa: debug
    org.apache.ibatis: debug
    com.baomidou.mybatisplus: debug
    org.springframework.jdbc: debug
  path: ./logs
com:
  alipay:
    sofa:
      rpc:
        enable-swagger: true
        registry-address: nacos://122.51.108.224:8848/public
      tracer:
        zipkin:
          base-url: http://122.51.108.224:9411
