spring:
  application:
    name: cloud-dubbo-provider
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://10.7.25.205:3306/workflow?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 10.7.25.201
    port: 7379
dubbo:
  enabled: false
  protocol:
    name: dubbo
    port: -1
  registry:
    address: zookeeper://122.51.108.224:2181
  application:
    environment:
server:
  port: 8080

mybatis-plus:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath*:/mapper/**/*.xml
logging:
  level:
    root: INFO
    com.open.cloud.dubbo.provider.dao: DEBUG
    org.mybatis: debug
    org.apache.ibatis: debug
    com.baomidou.mybatisplus: debug
    org.springframework.jdbc: debug
