spring:
  application:
    name: cloud-dubbo-consumer
  cloud:
    nacos:
      discovery:
        server-addr: nacos.didispace.com:80
dubbo:
  protocol:
    name: dubbo
    port: -1
  registry:
    address: spring-cloud://nacos.didispace.com
server:
  port: 8002
