spring:
  application:
    name: cloud-dubbo-consumer
eureka:
  instance:
    hostname: ${spring.cloud.client.ip-address}
    prefer-ip-address: true
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    enabled: true
    service-url:
      defaultZone: http://122.51.108.224:8001/eureka/
dubbo:
  scan:
    base-packages: om.open.cloud.dubbo.consumer
  protocol:
    name: dubbo
    port: -1
  registry:
    address: spring-cloud://localhost
server:
  port: 8081
feign:
  hystrix:
    enabled: true
