spring:
  application:
    name: cloud-eureka-server

server:
  port: 8001

eureka:
  instance:
    hostname: eureka1
    prefer-ip-address: true
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka2:8002/eureka/,http://eureka3:8003/eureka/
    use-dns-for-fetching-service-urls: false
  server:
    use-read-only-response-cache: false
    enable-self-preservation: true